# Numpy Tutorial
######
## Creator: Mobin Soleimani
##### My Github: Mobinsoleimani
##### My Linkedin : www.linkedin.com/in/mobin-soleimani
##### contact me : soleimanimobin15@gmail.com


### import packages

In [1]:
import numpy as np

# Numpy ndarray

#### The first step after installing NumPy is to create an array, as NumPy is primarily used for working with arrays.

In [2]:
d = np.array([[10,5,0.2,],[2,3.5,8]])

In [3]:
d

array([[10. ,  5. ,  0.2],
       [ 2. ,  3.5,  8. ]])

#### In NumPy, you can multiply a number with all elements of an array. This operation is vectorized, meaning there is no need to use loops.
#### For example:

In [4]:
d * 10

array([[100.,  50.,   2.],
       [ 20.,  35.,  80.]])

In [5]:
d * 2

array([[20. , 10. ,  0.4],
       [ 4. ,  7. , 16. ]])

#### And you can easily add two arrays together. It sounds interesting!

In [6]:
d + d

array([[20. , 10. ,  0.4],
       [ 4. ,  7. , 16. ]])

#### In NumPy, you can convert a Python list to an array.

In [7]:
data = [2,9,3,5,7,8,10]

In [8]:
arr1 = np.array(data)

In [9]:
arr1

array([ 2,  9,  3,  5,  7,  8, 10])

#### you can creat 2D array with np.array

In [10]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [11]:
arr2 = np.array(data2)

In [12]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

#### ndim represents the number of dimensions (axes) of the ndarray. 

In [13]:
arr2.ndim

2

#### shape in NumPy is an attribute of arrays that returns a tuple representing the dimensions of the array. This tuple shows how many elements the  array has in each dimension.

In [14]:
arr2.shape

(2, 4)

In [15]:
arr3 = np.array([1, 2, 3, 4, 5, 6, 7, 8])


In [16]:
arr3.shape

(8,)

#### With dtype, you can see the data type of the array. It can be str, int, float, or bool

In [17]:
d.dtype

dtype('float64')

In [18]:
arr = np.array([1, 2, 3])

In [19]:
arr.dtype

dtype('int32')

# Numpy zero and empty function

##### The np.zeros function is a widely used function in the NumPy library that allows us to create an array of specified dimensions, where all 
##### elements are initialized to zero. This function is particularly useful when we need an array with an initial value of zero to work as a placeholder or starting point.

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

##### empty in NumPy is a function used to create an uninitialized array. This means the array is created with a specified shape but without 
##### initializing its elements to any particular values. Instead, it contains whatever random data happens to be in the allocated memory at that moment.



In [21]:
np.empty((3))

array([1.49137488e-311, 0.00000000e+000, 4.94065646e-324])

##### The arange function is a function in numpy that creates an array as far as you specify

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### You can specify its type in numpy when you are creating an array with the dtype parameter 

In [23]:
arr= np.array([2,5,6,8],dtype = 'float')

In [24]:
arr.dtype

dtype('float64')

In [25]:
n = np.arange(10,dtype='u4')

In [26]:
n 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint32)

##### With numpy you can easily perform all kinds of mathematical operations on arrays
##### Like multiplication, addition and subtraction

In [27]:
arr **2

array([ 4., 25., 36., 64.])

In [28]:
arr - arr

array([0., 0., 0., 0.])

In [29]:
arr * arr

array([ 4., 25., 36., 64.])

##### And you can even specify bigger and smaller.Piece of cake

In [30]:
arr > 2


array([False,  True,  True,  True])

In [31]:
arr2= np.array([22,88,99,55])

In [32]:
arr > arr2

array([False, False, False, False])

# Indexing and slicing

In [33]:
r = np.arange(10)

In [34]:
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Here, with this method, the 5th index can be shown

In [35]:
r[5]

5

##### And you can change the value of your desired index like this

In [36]:
r[5] = 12

In [37]:
r

array([ 0,  1,  2,  3,  4, 12,  6,  7,  8,  9])

##### in NumPy (and Python in general), slicing is used to extract specific parts of an array. The syntax r[3:6] extracts a portion of the array, 
##### starting from index 3 (inclusive) and ending at index 6 (exclusive).

In [38]:
r[3:6]

array([ 3,  4, 12])

In [39]:
slice = r[3:6]

In [40]:
r

array([ 0,  1,  2,  3,  4, 12,  6,  7,  8,  9])

In [41]:
slice

array([ 3,  4, 12])

##### slice[:] is a way to select or access all elements of an array in NumPy (or in Python in general). It’s essentially a shorthand for selecting

#####  everything in a given dimension.

In [42]:
slice[:]

array([ 3,  4, 12])

##### And you can change the index like this.

In [43]:
slice[1] = 15

In [44]:
slice

array([ 3, 15, 12])

In [45]:
r

array([ 0,  1,  2,  3, 15, 12,  6,  7,  8,  9])

# 2D and 3D and slicing array 

In [46]:
arr2d = np.array([[2,1,3],[10,9,8],[2,3,7]])

In [47]:
arr2d

array([[ 2,  1,  3],
       [10,  9,  8],
       [ 2,  3,  7]])

##### In slicing 2D and 2D presentations, the first element becomes rows and the second element becomes columns like this:


In [48]:
arr2d[1,2]

8

##### arr2d[row, column]

In [49]:
arr3d = np.array([[[1,2,3],[2,56,9]],[[1,2,5],[8,7,9]]])

In [50]:
arr3d

array([[[ 1,  2,  3],
        [ 2, 56,  9]],

       [[ 1,  2,  5],
        [ 8,  7,  9]]])

##### In NumPy, when working with 3D arrays, the first index (like 0 in arr3d[0]) refers to the first "block" or "slice" along the first dimension of 

##### the array. This selects the entire 2D array (or "matrix") at that position.

In [51]:
arr3d[0]

array([[ 1,  2,  3],
       [ 2, 56,  9]])

#### Another example :

In [52]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]],[[58,6,9],[11,89,100]]])

In [53]:
arr3d[2]

array([[ 58,   6,   9],
       [ 11,  89, 100]])

##### 
In NumPy, it is possible to copy an array into a variable and modify its values. If you need to revert to the original values of the array, you 

##### can use the copied array to restore it.

### Note:
#### However, there’s an important distinction between making a reference (just pointing to the same array) and making a copy (creating a new, independent array).

#### To ensure the original array is preserved, you should explicitly create a copy using the copy() method.


In [54]:
old = arr3d[0].copy()

In [55]:
arr3d[0] = 23

In [56]:
arr3d

array([[[ 23,  23,  23],
        [ 23,  23,  23]],

       [[  7,   8,   9],
        [ 10,  11,  12]],

       [[ 58,   6,   9],
        [ 11,  89, 100]]])

In [57]:
arr3d[0] = old

In [58]:
arr3d

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]],

       [[ 58,   6,   9],
        [ 11,  89, 100]]])

##### In a 3D NumPy array, the syntax arr3d[1,1] is used to access a specific row from a specific "block" (or slice) of the array. It selects the row 

##### at index 1 (second row) from the "block" at index 1 (second block).



In [59]:
arr3d[1,1]

array([10, 11, 12])

In [60]:
arr2d

array([[ 2,  1,  3],
       [10,  9,  8],
       [ 2,  3,  7]])

##### In NumPy, arr2d[:2] is used for slicing rows in a 2D array. The :2 part means "select rows from the start up to (but not including) index 2."


In [61]:
arr2d[:2]

array([[ 2,  1,  3],
       [10,  9,  8]])

##### Another example:

In [62]:
arr2d[:1]

array([[2, 1, 3]])

##### This slicing operation is used to extract a subset of elements from a 2D NumPy array. It selects:
1.The first two rows (index 0 and 1), because of :2.

2.The columns starting from index 1 to the end, because of 1:.

##### This allows you to extract specific parts of the 2D array efficiently.

In [63]:
arr2d[:2,1:]

array([[1, 3],
       [9, 8]])

##### This slicing operation selects a specific subset of elements from a 2D NumPy array:
1. The row at index 1 (the second row), because of 1.

2. The first two columns (index 0 and 1), because of :2.

In [64]:
arr2d[1,:2]

array([10,  9])

##### The slicing operation arr2d[:, :1] is used to extract a specific subset of a 2D array. It selects:

1. All rows (:): Includes every row in the array.

2. The first column (:1): Selects columns starting from the beginning (index 0) up to (but not including) index 1. This effectively selects only the first column.

In [65]:
arr2d[:,:1]

array([[ 2],
       [10],
       [ 2]])

# Boolean indexing

##### In NumPy, you can use Boolean indexing to check whether a particular element is present and to find its location in the array. When you compare 

##### an element with a condition (like arr == value), it returns a Boolean array where True represents the locations where the condition holds (the element is present)and False where it doesn't.

##### Here's how you can check if an element is present and find its location:

In [66]:
name = np.array(['mobin','jack','mobin','ali','jasmin','hana'])

In [67]:
name == 'mobin'

array([ True, False,  True, False, False, False])

In [68]:
number = np.array([[1,3],[10,2],[3,2],[5,2],[7,3],[3,8]])

In [69]:
number

array([[ 1,  3],
       [10,  2],
       [ 3,  2],
       [ 5,  2],
       [ 7,  3],
       [ 3,  8]])

##### The expression number[name == 'mobin'] is a form of Boolean indexing in NumPy. It is used to filter or select elements from one array (number) 

##### based on a condition applied to another array (name).

In [70]:
number[name=='mobin']

array([[1, 3],
       [3, 2]])

##### and you can slice it

In [71]:
number[name=='mobin',1:]

array([[3],
       [2]])

##### The expression name != 'mobin' is a comparison operation in NumPy (or Python in general) that checks if each element in the name array is not 
##### equal to the string 'mobin'. The result is a Boolean array where each element is True if the corresponding element in name is not equal to 
##### 'mobin', and False if it is equal to 'mobin'.

In [72]:
name != 'mobin'

array([False,  True, False,  True,  True,  True])

##### You can also use ~ instead of != and it does the same thing

In [73]:
~(name =='mobin')

array([False,  True, False,  True,  True,  True])

In [74]:
number[name != 'mobin'] 

array([[10,  2],
       [ 5,  2],
       [ 7,  3],
       [ 3,  8]])

In [75]:
number[~(name =='mobin')] 

array([[10,  2],
       [ 5,  2],
       [ 7,  3],
       [ 3,  8]])

##### to Selecting two of the three names to combine multiple boolean conditions, use boolean arithmetic operators like & (and) and | (or)

In [76]:
msk = (name == 'mobin')|(name == 'jack')

In [77]:
msk

array([ True,  True,  True, False, False, False])

In [78]:
number[msk]

array([[ 1,  3],
       [10,  2],
       [ 3,  2]])

#####  number[name != 'mobin'] = 1: This code uses Boolean indexing in NumPy to modify specific values in the number array based on a condition applied 
##### to the name array.

#### How this work:

1. name != 'mobin':

   . This checks if each element in the name array is not equal to 'mobin'.
   
   . It returns a Boolean array of True and False. If an element is not equal to 'mobin', it will be True; otherwise, it will be False.

2.number[...]:


    . This part uses the Boolean array to index into the number array and selects elements where the condition is True.

3.= 1:

    .This assigns the value 1 to all the selected positions in the number array where the condition is True.


#### simple example:

In [79]:
name = np.array(['ali', 'mobin', 'sara', 'mobin'])

In [80]:
number = np.array([10, 20, 30, 40])

In [81]:
number[name != 'mobin'] = 3

In [82]:
number

array([ 3, 20,  3, 40])

#### Another example:

In [83]:
number[name != 'mobin'] = 1

In [84]:
number

array([ 1, 20,  1, 40])

# Fancy indexing :

### Note: 
##### Fancy indexing is a technique in NumPy that allows you to access multiple elements of an array at once using an array of indices, rather 

##### than a single index or a slice.



In [85]:
arr = np.zeros((8,4))

##### Creat a array in the range of 8

In [86]:
for i in range(8):
    arr[i] = i

In [87]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

##### Here, we use fancy indexing to return the elements at indices 2, 1, 5, and 7 from the array.

In [88]:
arr[[2,1,5,7]]

array([[2., 2., 2., 2.],
       [1., 1., 1., 1.],
       [5., 5., 5., 5.],
       [7., 7., 7., 7.]])

In [89]:
arr[[-2,-3,-6]]

array([[6., 6., 6., 6.],
       [5., 5., 5., 5.],
       [2., 2., 2., 2.]])

 # Transposing Array and Swapping Axes

##### The reshape function in NumPy allows you to change the shape of an array without changing its data. It is useful when you need to reorganize 

##### elements into a different structure, like converting a 1D array into a 2D or 3D array.

In [90]:
arr = np.arange(20).reshape((4,5))

In [91]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

##### In NumPy, a permutation is an operation that swaps the rows and columns of an array. Useful when working with matrices and multidimensional arrays.

##### In numpy you can do this with .T

In [92]:
arr.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

##### and you can use transpose() function for transposing array

In [93]:
np.transpose(arr)

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

##### np.dot() returns the dot product of vectors a and b.

In [94]:
arr = np.array([[1,5,3],[8,5,7],[9,10,2]])

In [95]:
arr

array([[ 1,  5,  3],
       [ 8,  5,  7],
       [ 9, 10,  2]])

In [96]:
np.dot(arr.T,arr)

array([[146, 135,  77],
       [135, 150,  70],
       [ 77,  70,  62]])

##### You can also use @ instead of np.dot

In [97]:
arr.T @ arr

array([[146, 135,  77],
       [135, 150,  70],
       [ 77,  70,  62]])

##### The swapaxes() function in NumPy is used to swap two axes (dimensions) of an array. It is useful when working with multi-dimensional arrays, 

##### where you need to rearrange data without changing the actual values. 

In [98]:
arr.swapaxes(0,1)

array([[ 1,  8,  9],
       [ 5,  5, 10],
       [ 3,  7,  2]])

# Pseudorandom Number Generation :

#### Note :
##### In NumPy, pseudorandom numbers are generated using the random module, specifically numpy.random. These numbers are not truly random but are 

##### generated using a deterministic algorithm based on a seed value.



##

##### This function generates a 2D array (shape 2×4) of random numbers drawn from a standard normal distribution.

#### Note:
##### standard_normal()  Generates random numbers from a normal distribution 

In [99]:
arr = np.random.standard_normal(size=(2,4))

In [100]:
arr

array([[ 0.55574009,  1.63191896, -0.08037153,  0.19127568],
       [-1.30097956, -1.99523285,  0.09465933, -0.02996521]])

#### In NumPy, starting from version 1.17, a new random number generation system was introduced with the default_rng() function. This new approach 

##### offers better performance, and more control, and is intended to replace older functions like np.random.randn() and np.random.standard_normal().

1.np.random.default_rng(seed=12345):

    . default_rng() creates a Random Generator (RNG) object. This object provides methods to generate random numbers.

    . seed=12345: The seed ensures reproducibility, meaning you will get the same sequence of random numbers each time the code is run.
      Setting the seed ensures that the random number generation is deterministic.

2.rng.standard_normal((2,3))

    . standard_normal() generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).

    . (2, 3): This argument specifies that you want a 2×3 array (2 rows and 3 columns).


In [101]:
rng = np.random.default_rng(seed=12345)

test = rng.standard_normal((2,3))

In [102]:
test

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465]])

# Universal Functions: Fast Element-Wise Array Functions
 A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays. You can think of them as fast vectorized wrappers for simple functions that take one or more scalar values and produce one or more scalar results.

In [103]:
example = np.arange(10) 

In [104]:
example

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### The function np.sqrt() in NumPy is used to compute the square root of each element in the input array example. It works element-wise, meaning it 

##### applies the square root operation to each element of the array individually.



In [105]:
np.sqrt(example)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

##### The function np.exp() in NumPy is used to compute the exponential of each element in the input array example. Specifically, it calculates 
##### where e is the base of the natural logarithm (approximately 2.71828), and x is the value of each element in the array.

In [106]:
np.exp(example)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [107]:
x = rng.standard_normal(8)

In [108]:
y = rng.standard_normal(8)

In [109]:
x

array([-1.3677927 ,  0.6488928 ,  0.36105811, -1.95286306,  2.34740965,
        0.96849691, -0.75938718,  0.90219827])

In [110]:
y

array([-0.46695317, -0.06068952,  0.78884434, -1.25666813,  0.57585751,
        1.39897899,  1.32229806, -0.29969852])

##### The function np.maximum(x, y)  used to compare two arrays (or scalars) element-wise and return an array where each element is the maximum of the 

##### corresponding elements from x and y.

##### In other words, for each pair of elements from x and y, it selects the larger one and creates a new array with those values.

In [111]:
np.maximum(x,y)

array([-0.46695317,  0.6488928 ,  0.78884434, -1.25666813,  2.34740965,
        1.39897899,  1.32229806,  0.90219827])

# Expressing Conditional Logic as Array Opreations

##### NumPy allows us to apply conditional logic directly on arrays without using loops, making computations faster and more efficient. This is useful 

##### for tasks like filtering, replacing values, and conditional transformations.



In [115]:
arr= rng.standard_normal((5,5))

In [116]:
arr

array([[ 1.34707776,  0.06114402,  0.0709146 ,  0.43365454,  0.27748366],
       [ 0.53025239,  0.53672097,  0.61835001, -0.79501746,  0.30003095],
       [-1.60270159,  0.26679883, -1.26162378, -0.07127081,  0.47404973],
       [-0.41485376,  0.0977165 , -1.64041784, -0.85725882,  0.68828179],
       [-1.15452958,  0.65045239, -1.38835995, -0.90738246, -1.09542531]])

In [117]:
arr > 0

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True],
       [False,  True, False, False,  True],
       [False,  True, False, False,  True],
       [False,  True, False, False, False]])

##### The function np.where(condition, x, y) works like an if-else statement applied element-wise to a NumPy array.

#### for Example:

In [118]:
np.where(arr > 0,1,0)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 0, 1],
       [0, 1, 0, 0, 1],
       [0, 1, 0, 0, 1],
       [0, 1, 0, 0, 0]])

# Mathmatical and Statistical Methods

In [119]:
arr = rng.standard_normal((5,5))

In [120]:
arr

array([[ 7.14569494e-03,  5.34359903e-01, -1.06580785e+00,
        -1.81472740e-01,  1.62195180e+00],
       [-3.17391946e-01, -8.15814967e-01,  3.86579017e-01,
        -2.23638926e-01, -7.01690809e-01],
       [-1.79571318e+00,  8.18325622e-01, -5.71032902e-01,
         7.85525063e-04, -1.06364272e+00],
       [ 1.30171450e+00,  7.47872942e-01,  9.80875909e-01,
        -1.10418688e-01,  4.67918531e-01],
       [ 8.90607150e-01,  1.02300937e+00,  3.12383389e-01,
        -6.19046857e-02, -3.59479647e-01]])

##### The mean() function calculates the average (arithmetic mean) of the elements in a NumPy array.

In [109]:
np.mean(arr)

-0.19343652888887364

##### The sum() function calculates the sum of an array

In [110]:
np.sum(arr)

-4.835913222221841

##### The np.mean(arr, axis=1) function calculates the mean (mean) along the rows in a 2D NumPy array. And we can count any row we want


In [121]:
np.mean(arr,axis = 1)

array([ 0.18323536, -0.33439153, -0.52225553,  0.67759264,  0.36092311])

##### You can also use it for sum()

In [122]:
np.sum(arr,axis = 0)

array([ 0.08636222,  2.30775287,  0.04299757, -0.57664951, -0.03494284])

# Methods for Boolean Arrays

In [123]:
arr = rng.standard_normal(100)

In [114]:
arr

array([ 7.14569494e-03,  5.34359903e-01, -1.06580785e+00, -1.81472740e-01,
        1.62195180e+00, -3.17391946e-01, -8.15814967e-01,  3.86579017e-01,
       -2.23638926e-01, -7.01690809e-01, -1.79571318e+00,  8.18325622e-01,
       -5.71032902e-01,  7.85525063e-04, -1.06364272e+00,  1.30171450e+00,
        7.47872942e-01,  9.80875909e-01, -1.10418688e-01,  4.67918531e-01,
        8.90607150e-01,  1.02300937e+00,  3.12383389e-01, -6.19046857e-02,
       -3.59479647e-01, -7.48643984e-01, -9.65478907e-01,  3.60034657e-01,
       -2.44552532e-01, -1.99585661e+00, -1.55247617e-01,  1.06383087e+00,
       -2.75171567e-01, -1.85333593e+00, -1.24341928e-01,  7.84974522e-01,
        2.01998597e-01, -4.28074443e-01,  1.84828890e+00,  1.89995289e+00,
       -9.84250348e-02,  8.13445440e-01,  3.92494389e-01,  7.81442900e-01,
        1.45327152e+00,  8.20186045e-01,  8.77053446e-02, -6.53505648e-01,
       -8.11886879e-01, -2.55381724e-02,  1.15818454e+00,  3.00520870e-01,
        5.30566461e-02,  

##### This expression counts the number of positive elements in a NumPy array.

In [115]:
(arr > 0).sum()

49

##### This expression calculates the proportion of elements in arr that are less than or equal to 0.

In [116]:
(arr <= 0).mean()

0.51

In [117]:
(arr <= 0).sum()

51

In [125]:
bools = np.array([True,True,True,False])

##### The .any() function in NumPy checks if at least one True value exists in a Boolean array. If at least one element is True, it returns True; 

##### otherwise, it returns False.



In [126]:
bools.any()

True

##### The .all() function in NumPy checks if all elements in a Boolean array are True

. Returns True if every element in the array is True.

. Returns False if at least one element is False.

In [127]:
bools.all()

False

# Sorting

In [130]:
arr = rng.standard_normal((5,3))

In [131]:
arr

array([[ 0.21605944, -0.96482356, -0.5566078 ],
       [-2.29838764, -0.73208213,  0.7364691 ],
       [ 0.46571672, -0.10787605, -0.34143629],
       [ 1.58453379,  0.28224121,  0.90954639],
       [ 0.39507157, -0.66937652,  1.55536898]])

In [132]:
np.sort(arr)

array([[-0.96482356, -0.5566078 ,  0.21605944],
       [-2.29838764, -0.73208213,  0.7364691 ],
       [-0.34143629, -0.10787605,  0.46571672],
       [ 0.28224121,  0.90954639,  1.58453379],
       [-0.66937652,  0.39507157,  1.55536898]])

##### arr.sort(axis = 0) sort values with each column 

In [133]:
np.sort(arr,axis = 0)

array([[-2.29838764, -0.96482356, -0.5566078 ],
       [ 0.21605944, -0.73208213, -0.34143629],
       [ 0.39507157, -0.66937652,  0.7364691 ],
       [ 0.46571672, -0.10787605,  0.90954639],
       [ 1.58453379,  0.28224121,  1.55536898]])

##### and np.sort(axis = 1) sort each rows

In [134]:
np.sort(arr,axis = 1)

array([[-0.96482356, -0.5566078 ,  0.21605944],
       [-2.29838764, -0.73208213,  0.7364691 ],
       [-0.34143629, -0.10787605,  0.46571672],
       [ 0.28224121,  0.90954639,  1.58453379],
       [-0.66937652,  0.39507157,  1.55536898]])

# Unique and Other set Logic

In [126]:
names = np.array(['bob','bob','joe','jack','bob','joe','bob','bob',])

##### The np.unique() function returns the unique elements from an array, sorted in ascending order. It removes any duplicate values in the array.

In [127]:
name = np.unique(names)

In [128]:
name

array(['bob', 'jack', 'joe'], dtype='<U4')

##### Another example :

In [135]:
num = np.array([1,5,2,2,2,3,3,5])

In [136]:
np.unique(num)

array([1, 2, 3, 5])

##### The np.in1d() function checks whether elements of one array are present in another array. It returns a Boolean array.

In [137]:
np.in1d(num,[3,2])

array([False, False,  True,  True,  True,  True,  True, False])

In [138]:
a = np.array([1,5,9,6,3,2,4,8,4])

In [139]:
a

array([1, 5, 9, 6, 3, 2, 4, 8, 4])

# File input and output with Arrays

##### you can save file with np.save() function

In [155]:
np.save('my_arr',a)

##### and you can load file with np.load()

In [156]:
np.load('my_arr.npy')

array([1, 5, 9, 6, 3, 2, 4, 8, 4])

##### You save multiple arrays in an uncompressed archive using np.savez and passing the arrays as keyword arguments

In [160]:
x = np.arange(10)

In [161]:
z = np.arange(10,20)

In [167]:
np.savez('my_duble_arr.npz',a=x ,b=z)

In [170]:
load = np.load('my_duble_arr.npz')

In [172]:
load['b']

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# Linear Algebra

In [144]:
a = np.array(([1,5,9],[3,7,8]))

In [145]:
a

array([[1, 5, 9],
       [3, 7, 8]])

In [146]:
b = np.array(([2,6],[15,8],[12,10]))

In [147]:
b

array([[ 2,  6],
       [15,  8],
       [12, 10]])

##### As I said before In NumPy, the dot() function is used to perform matrix multiplication (dot product) between two arrays. It can also be used for 

##### vector multiplication or inner product.



In [148]:
a.dot(b)

array([[185, 136],
       [207, 154]])

##### You can use np.dot(a,b) instead of a.dot(b).

In [149]:
np.dot(a,b)

array([[185, 136],
       [207, 154]])

##### The @ operator in Python is used for matrix multiplication, and it is essentially a shorthand for the np.dot() function when working with NumPy 

##### arrays. This operator was introduced in Python 3.5 to allow matrix multiplication in a more intuitive way, especially for linear algebra operations.



In [195]:
a @ np.ones(3)

array([15., 18.])

##

### Congratulations! 🎉 You have learned the basics of NumPy, one of the most powerful libraries for numerical computing in Python. 

#### If you have any questions or feedback, you can contact me via email.

### Good luck, and happy coding! 🚀



##### Final Tip: If you want to learn more, remember the NumPy documentation is a great resource: https://numpy.org/doc/stable/

##### In memory of Haj Ali